# Generated by Django 3.2.10 on 2022-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_photo_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo_add',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
